### PR TITLE
go to page #60

### PR DESCRIPTION
**Pull request by Benjaneer**
this also has my suggestions for [ToC... #58]

### CODE REVIEW

**Comment by Benjaneer** [comment]
I also dropped in image scale to fit (Image resize #2), if you don't want that just take it out of the css

**Comment by Benjaneer** [comment]
damn, just found out it only loads 6 pages at a time, so if the ToC and target page are not loaded then it can't find them in the lookup, I'm going to try adding a lookup list in the html...

**Comment by Benjaneer** [comment]
got it, I added a lookup list of all pages into the html and then used it in the javascript :D

**Comment by Xbozon** [comment]
@Benjaneer Hello, I checked PR, and it has some isssues:
1. After scrolling to the specific page and back to the title, page scrolling stop working.
2. Some margin issues.

Can you check these problems, or do you need any help with them? 

image

**Comment by Benjaneer** [comment]
... oh you mean from the ToC, I did notice that, it also does not work from the ToC if you open the journal when it's on another page already, it only works from ToC if you open the journal and it's on the ToC.  However links in other pages or journals always work.  (I couldn't figure out the ToC thing, but since the others worked I wasn't that worried about it, I was actually thinking I'd remove the ToC from the template for myself because I can just make my own as one of the pages.)

I've actually adjusted the margins because the mod as downloaded doesn't line up for me.
(I forgot that was in there; this is how it looks for me with no other mods and none of my changes)
image

**Comment by Benjaneer** [comment]
oh, that's interesting, the ToC issue doesn't occur if there are six or less pages (not counting the ToC itself).  Also the edit buttons stop working past page six... but that seems to be a pre-existing issue, probably related...

**Pull request closed without merging**
