### PR TITLE
please consider

### PR DESCRIPTION
**Pull request by Benjaneer**
Screenshot_2022-09-06_20_48_25
Screenshot_2022-09-06_20_47_56
Screenshot_2022-09-06_20_45_32
Screenshot_2022-09-06_20_45_00

### CODE REVIEW

**Comment by Benjaneer** [comment]
also added page turning tabs in the lower corners, they lookup the entry name and append a "1" or add 1 for next page and subtract or remove the number for previous

https://user-images.githubusercontent.com/9536408/189500405-65e6c916-a711-48dd-8658-7928bab934aa.mp4

**Comment by Xbozon** [comment]
@Benjaneer 

Thank you very much for your work, but I have to finish with the fixes for v10 first :(

**Comment by Benjaneer** [comment]
added a book cover, text on top of image (maybe difficult/impossible to change image while in this style though), invisible page-turn tabs are also still in the corners
Screenshot_2022-09-24_19-39-27

**Comment by Benjaneer** [comment]
I still haven't patched to v10 or I'd try to help with that.

**Comment by Xbozon** [comment]
@Benjaneer 
Hello, I have finished the basic changes for v10, however they are not compatible with this MR. From the good news, focusing on your MR, I was able to recreate some of the features you need. 
I suggest waiting for the v10 release and then see what is missing. Okay?

**Comment by Benjaneer** [comment]
np, I've been thinking I'll just stick with v9, but feel free to use or cannibalize as much or as little as you like from the MR.

**Comment by Xbozon** [comment]
Thanks for taking the time to PR, but for a better experience with custom journals, I've added an API, I'd love for you to check it out and take advantage of it. 

https://github.com/Xbozon/storyteller-addon-example

I'm open to any questions.

**Comment by Benjaneer** [comment]
That page turn is exquisite.  I can see you're still hammering out the alignment and stuff, but I love it.
image

**Comment by Xbozon** [comment]
@Benjaneer 

I sometimes catch this bug in turn.js (third-party library), so far I can't fix it. It occurs mostly if you use foundry as a separate program, not in the browser.

Do you have a different situation?

**Comment by Benjaneer** [comment]
that is how I use it, I also noticed that it only happens on page2 lower left corner (turning from bottom to table of contents)

**Comment by Benjaneer** [comment]
I've also noticed that my page editor doesn't look like you have pictured in the readme

**Pull request closed without merging**
